
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-6
pull_requests: [{"author":{"id":"U_kgDOBXuvjg","is_bot":false,"login":"emanbareket","name":""},"headRefName":"Immanuel-READMEFixes","number":36,"title":"Immanuel readme fixes","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/36"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-HomeController","number":34,"title":"Finished Home Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/34"},{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-PublicHoliday-Controller","number":33,"title":"Add controller for Public Holiday API and Controller Branch","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/33"}]
