
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-6
pull_requests: [{"author":{"id":"U_kgDOBXuvwQ","is_bot":false,"login":"brycewangg","name":"Bryce Wang"},"headRefName":"Bryce-Tides-Controller","number":32,"title":"Add Tides Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/32"},{"author":{"id":"U_kgDOB740jQ","is_bot":false,"login":"sawyerrice","name":""},"headRefName":"Sawyer-Joke-Controller","number":31,"title":"Add Joke Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/31"},{"author":{"id":"U_kgDOBXuvwQ","is_bot":false,"login":"brycewangg","name":"Bryce Wang"},"headRefName":"Bryce-Tides","number":29,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/29"},{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-PublicHoliday","number":28,"title":"Add Public Holiday Service and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/28"},{"author":{"id":"U_kgDOB740jQ","is_bot":false,"login":"sawyerrice","name":""},"headRefName":"Sawyer-Joke","number":26,"title":"Add Joke Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/26"}]
