
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-6
pull_requests: [{"author":{"id":"U_kgDOB740jQ","is_bot":false,"login":"sawyerrice","name":""},"headRefName":"Sawyer-Joke","number":25,"title":"Add joke service and controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/25"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-HomeController","number":22,"title":"Add Home Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/22"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-Location-Controller","number":21,"title":"Add Location Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-6/pull/21"}]
